name: Benchmark metal gha staging
on:
  workflow_dispatch: {}

jobs:
  isolated:
    name: Depot Cacheless (isolated ${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: production
            runner: depot-ubuntu-24.04
          - target: staging
            runner: depot-ubuntu-24.04,connection=gha-staging
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build -x test

  depot-cacheless:
    name: Depot Cacheless (${{ matrix.attempt }}, ${{ matrix.multiplier }}x)
    needs: isolated
    runs-on: depot-ubuntu-24.04,connection=gha-staging
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        attempt:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
        multiplier: [1, 2, 3, 4, 5]
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build -x test
