name: Benchmark - Build
on:
  push: {}
  workflow_dispatch: {}

jobs:
  depot-remote-cache:
    name: Depot with Remote Cache
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: ~/.gradle/init.gradle
          old-string: "if (!settings.buildCache?.remote) {"
          new-string: "if (true) {"
      - run: ./gradlew --build-cache build

  depot-cacheless:
    name: Depot Cacheless
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build

  github-local-cache:
    name: Github with Local Cache
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - run: ./gradlew build

  github-cacheless:
    name: Github Cacheless
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build
